ecommerce_project/cart/urls.py
from . import views
from django.urls import path
app_name = 'cart'


urlpatterns = [
     path('add/<int:product_id>/',views.add_cart,name='add_cart'),
     path('',views.cart_detail,name='cart_detail'),
     path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
     path('full_remove/<int:product_id>/',views.full_remove,name='full_remove'),

]

ecommerce_project/ecommerce_app/urls.py
from . import views
from django.urls import path, include
app_name= 'ecommerce_app'

urlpatterns = [
    path('',views.allProdCat,name='allProdCat'),
    path('<slug:c_slug>/',views.allProdCat,name='product_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/',views.proDetail,name='prodCatDetail'),

]

ecommerce_project/ecommerce_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('ecommerce_app.urls')),
    path('search/', include('search_app.urls')),
    path('cart/', include('cart.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce_project/search_app/urls.py
from . import views
from django.urls import path
app_name = 'search_app'


urlpatterns = [
    path('',views.SearchResult,name='SearchResult'),

]

ecommerce_project/cart/models.py
from django.db import models

# Create your models here.
from ecommerce_app.models import Product


class Cart(models.Model):
    objects = None
    cart_id = models.CharField(max_length=250,blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)


class CartItem(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.product)

ecommerce_project/ecommerce_app/models.py
from django.db import models
from django.urls import reverse


# Create your models here.


class Category(models.Model):
    objects = None
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=300,unique=True)
    description=models.TextField(blank=True)
    image=models.ImageField(upload_to='category',blank=True)

    class Meta:
        ordering= ('name',)
        verbose_name='Category'
        verbose_name_plural='Categories'

    def get_url(self):
        return reverse('ecommerce_app:product_by_category',args=[self.slug])

    def __str__(self):
        return'{}'.format(self.name)


class Product(models.Model):
    objects = None
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    image=models.ImageField(upload_to='product',blank=True)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)

    class Meta:
        ordering=('name',)
        verbose_name='Product'
        verbose_name_plural='Products'

    def get_url(self):
        return reverse('ecommerce_app:prodCatDetail',args=[self.category.slug, self.slug])

    def __str__(self):
        return '{}'.format(self.name)

ecommerce_project/search_app/models.py
from django.db import models

# Create your models here.

ecommerce_project/cart/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.core.exceptions import ObjectDoesNotExist
from ecommerce_app.models import Product
from . models import Cart,CartItem

# Create your views here.
# creating session for cart_id


def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request,product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(cart_id=_cart_id(request))
        cart.save()
    try:
       cart_item = CartItem.objects.get(product=product,cart=cart)
       if cart_item.quantity < cart_item.product.stock:
           cart_item.quantity += 1
           cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(product=product,quantity=1,cart=cart)
        cart_item.save()

    return redirect('cart:cart_detail')


def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart = Cart.objects.get(cart_id = _cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(cart_items=cart_items,total=total,counter=counter))


def cart_remove(request,product_id):
    cart = Cart.objects.get(cart_id = _cart_id(request))
    product = get_object_or_404(Product,id= product_id)
    cart_item = CartItem.objects.get(product= product, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')


def full_remove(request,product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

ecommerce_project/ecommerce_app/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404

from .models import Category, Product

from django.core.paginator import Paginator, EmptyPage, InvalidPage
# Create your views here.


def allProdCat(request, c_slug=None):
    c_page = None
    product_list = None

    if c_slug != None :
        c_page = get_object_or_404(Category, slug=c_slug)
        product_list = Product.objects.all().filter(category=c_page, available=True)
    else:
        product_list = Product.objects.all().filter(available=True)
    paginator=Paginator(product_list, 6)
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
    try:
        products = paginator.page(page)
    except(EmptyPage,InvalidPage):
        products= Paginator.page(paginator.num_pages)
    return render(request, 'category.html', {'category': c_page, 'product': products})


def proDetail(request, c_slug, product_slug):
    try:
        product = Product.objects.get(category__slug=c_slug, slug=product_slug)
    except Exception as e:
        raise e
    return render(request, 'product.html', {'product': product})

ecommerce_project/search_app/views.py
from django.shortcuts import render
from ecommerce_app.models import Product
from django.db.models import Q
# Create your views here.


def SearchResult(request):
    products = None
    query = None
    if 'q' in request.GET:
        query = request.GET.get('q')
        products = Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
    return render(request,'Search.html',{'query': query, 'product': products})

ecommerce_project/templates/base.html
{% load static %}
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" >
    <link href="{% static 'css/custom.css' %}" rel="stylesheet" >
    <script src="https://kit.fontawesome.com/a4f4d6d130.js" crossorigin="anonymous"></script>
    <meta name="description" content="{%block metadescription %}{% endblock %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
{% include 'header.html' %}
{% include 'nav.html' %}
<div class="container">
{% block content %}
{% endblock %}
</div>
{% include 'footer.html' %}
<script src="{% static 'js/popper.min.js' %}" ></script>
<script src="{% static 'js/bootstrap.min.js' %}" ></script>
</body>
</html>

ecommerce_project/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
   This is the Cart. Proceed to review your items and Place the order
{% endblock %}
{% block title %}
    Cart - E-Bin Companies PVT. LTD.
{% endblock %}
{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">Your shopping cart is Empty</h1>
        <br>
        <p class="text-center">
            Please click <a href="{% url 'ecommerce_app:allProdCat' %}">Here </a> to continue shopping
        </p>
    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">Your shopping cart</h1>
        <br>
    </div>
</div>
<div class="row mx-auto ">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
            <tr>
                <th colspan="5">
                    Your Items
                </th>
            </tr>
            </thead>
            <tbody>
            {% for cart_item in cart_items %}
            <tr>
                <td>
                    <a href="cart_item.product.get_absolute_url">
                        <img src="{{cart_item.product.image.url}}" alt="" class="float-left rounded" style="width:50px;height:50px;">
                    </a>
                </td>
                <td class="text-left my_custom_text">
                    <b>{{cart_item.product.name}}</b>
                    <br>
                    SKU:{{cart_item.product.id}}
                    <br>
                    Price:{{cart_item.product.price}}
                    <br>
                    Quantity:{{cart_item.quantity}} * RS {{cart_item.product.price}}

                </td>
                <td class="text-center">
                    <br><br>
                    <i class="fa-solid fa-indian-rupee-sign"></i>{{cart_item.sub_total}}
                </td>
                {% if cart_item.quantity < cart_item.product.stock %}
                <td>
                    <a href="{% url 'cart:add_cart' cart_item.product.id %}"></a>
                </td>
                <td>
                    <a href="{% url 'cart:add_cart' cart_item.product.id%}" class="custom_a">
                        <i class="fa fa-plus custom_icon"></i>
                    </a>
                    <br>
                    <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a">
                        <i class="fa fa-minus custom_icon"></i>
                    </a>
                    <br>
                    <a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_a">
                        <i class="fa fa-trash custom_icon"></i>
                    </a>
                    <br>
                </td>
                {% else %}
                <td>
                    <a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a">
                        <i class="fa fa-minus custom_icon"></i>
                    </a>
                    <br>
                    <a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_a">
                        <i class="fa fa-trash custom_icon"></i>
                    </a>
                    <br>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
            <tr>
                <th>
                    CHECK OUT
                </th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>
                    Please review your shopping cart item before proceeding with order payment
                </td>
            </tr>
            <tr>
                <td class="text-center">
                    Your Total is:<strong>{{ total }}</strong>
                </td>
            </tr>
            </tbody>
        </table>
        <div class="mx-auto m-5">
            <a href="{% url 'ecommerce_app:allProdCat' %}" class="btn btn-secondary btn-block my_custom_button">
                Continue Shopping
            </a>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

ecommerce_project/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
{% if category %}
    {{category.description | truncatewords:153 }}
{% else %}
    Welcome to E-Bin store, Where you can buy different trends
{% endif %}
{% endblock %}
{% block title %}
{% if category %}
    {{category.name }} - E-Bin Store
{% else %}
    See our new collection - E-Bin Store
{% endif %}
{% endblock %}
{% block content %}
{% if category %}
    <div class="row my_row_class">
        <div class="mx-auto">
            <p><a href="{% url 'ecommerce_app:allProdCat' %}">Our Product Collection</a></p>
        </div>
    </div>
{% endif %}
<div class="mx-auto">
    {% if category %}
    <img class="my_image" src="{{ category.image.url }}" alt="{{ category.name }}">
</div>
<br>
<div>
    <h1 class="my_title text-center">{{category.name }}</h1>
    <p class="text-justify">{{category.description}}</p>
</div>
{% else %}
<div>
    <img src="{% static 'img/banner.png' %}" alt="Our Products" style="margin-top:15px;" width="100%">
</div>
<br>
<div>
    <h1 class="text-center">Our Products Collection</h1>
    <p class="text-justify">There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.</p>
</div>
{% endif %}

<div class="container">
    <div class="row mx-auto">

            {% for product in product.object_list %}
        <div class="my-bottom-margin col-9 col-sm-12 col-md-4 col-lg-4 col-md-auto">
                <div class="card" style="width: 18rem;">
                  <a href="{{product.get_url}}"><img class="card-img-top" src="{{product.image.url}}" alt="{{product.name}}" style="max-height:230px;"></a>
                  <div class="card-body">

                    <p class="card-text">{{product.name | truncatewords:9 }}</p>
                  </div>
                  <ul class="list-group list-group-flush">
                    <li class="list-group-item"><b>{{product.price}}</b></li>
                  </ul>
                </div>
            </div>
            {% endfor %}

    </div>
    <div class="mx-auto">
        {% if product.paginator.num_pages > 1 %}
        <div class="text-center">
        {% for pg in product.paginator.page_range %}
            <a href="?page={{pg}}" class="btn btn-light btn-sm {% if product.number == pg %} active {% endif %}" > {{ pg }}</a>
        {% endfor %}
        </div>
        {% endif %}
    </div>
</div>










<!--<div class="container">-->
<!--    <div class="row mx-auto">-->
<!--        <div class="my-bottom-margin col-9 col-sm-12 col-md-4 col-lg-4">-->
<!--        {% for product in product %}-->
<!--        <div class="card shadow text-center" style="min-width:10rem;">-->
<!--            <a href="{{product.get_url}}">-->
<!--                <img class="card-image" src="{{product.image.url}}" alt="{{product.name}}">-->
<!--            </a>-->
<!--        <div class="card-body">-->

<!--                <h4>{{product.name}}</h4>-->
<!--                <p>{{product.price}}</p>-->

<!--             </div>-->

<!--            </div>-->
<!--            <br>-->
<!--            {% endfor %}-->
<!--         </div>-->

<!--    </div>-->
<!--</div>-->

{% endblock %}

ecommerce_project/templates/footer.html
<div class="container">
    <div class="my_footer navbar-fixed-bottom" style="background-color:#f9efea;">
        <center>
        <p>@Copy; E-Bin Companies Pvt. Ltd., All Rights Reserved</p>
        </center>
    </div>
</div>

ecommerce_project/templates/header.html
{% load static %}
<header>
    <center>
        <a href="{% url 'ecommerce_app:allProdCat' %}"><img src="{% static 'img/logo.png' %}" alt="logo" width="50px"></a>
    </center>
</header>

ecommerce_project/templates/nav.html
<div class="container p-3">
<nav class="navbar navbar-expand-lg bg-body-tertiary " style="background-color:#f7f7f7;" >
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
<!--        <li class="nav-item">-->
<!--          <a class="nav-link" href="#">Link</a>-->
<!--        </li>-->
        <li class="nav-item dropdown">
            {% if 'ecommerce_app' in request.path %} active {% endif %}
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Shop
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'ecommerce_app:allProdCat' %}">All Products</a></li>
              {% for cat in links %}
            <li>
                <a class="dropdown-item" href="{{ cat.get_url }}">{{ cat.name }}</a></li>
              {% endfor %}
          </ul>
        </li>
        {% if item_count > 0 %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cart:cart_detail' %}"><i class="fa-solid fa-cart-shopping"></i>({{item_count}})</a>
        </li>
        {% endif %}
      </ul>
      <form class="d-flex m-3" role="search" action="{% url 'search_app:SearchResult' %}" method="get">
        <input class="form-control me-2" type="search" placeholder="Search" name='q' aria-label="Search">
        <button class="btn btn-outline-success" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
      </form>
    </div>
  </div>
</nav>
</div>

ecommerce_project/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {{product.description | truncatewords:153 }}
{% endblock %}
{% block title %}
    {{product.name }} - E-Bin Store
{% endblock %}
{% block content %}
<div>
    <div>
        <p><a href="{% url 'ecommerce_app:allProdCat' %}">Home</a> | <a href="{{product.category.get_url}}">{{ product.category }}</a> {{ product.name }} </p>
    </div>
</div>
<br>
<div class="container">
    <div class="row">
        <div class="card mb-3" >
  <div class="row no-gutters">
    <div class="col-md-4">
      <img src="{{product.image.url}}" alt="{{product.name}}" style="width:80%;padding-top:30px;">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h2 class="card-title">{{ product.name }}</h2>
               <br>
          <p><b>Product Description:</b></p>
        <p class="card-text">{{product.description}}</p>
          <h3>Price:{{product.price}}</h3>
          <br>
        <p class="card-text"><small class="text-muted">
            {% if product.stock <= 0 %}
            <b>Out of Stock</b>
            {% else %}
            <a href="{% url 'cart:add_cart' product.id %}" class="btn btn-primary"> Add to Cart</a>
            {% endif %}
        </small></p>
      </div>
    </div>
  </div>
</div>
</div>
</div>








<!--<div class="container">-->
<!--    <div class="row">-->
<!--        <div>-->
<!--            <img src="{{product.image.url}}" alt="{{product.name}}">-->
<!--        </div>-->
<!--    </div>-->
<!--    <div>-->
<!--        <div>-->
<!--            <h1>{{product.name}}</h1>-->
<!--            <p>Price:{{product.price}}</p>-->
<!--            <p> Product Description</p>-->
<!--            <p>{{product.description}}</p>-->
<!--            {% if product.stock <= 0 %}-->
<!--            <p><b>Out of Stock</b></p>-->
<!--            {% else %}-->
<!--            <a href=""> Add to Cart</a>-->
<!--            {% endif %}-->
<!--        </div>-->
<!--    </div>-->
<!--</div>-->
{% endblock %}

ecommerce_project/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    We have variety of products
{% endblock %}
{% block title %}
    Search
{% endblock %}
{% block content %}
<div>
    <p class="text-center my_search_text"> You have searched for:<b>"{{ query }}"</b> </p>
</div>

<div class="container">
    <div class="row mx-auto">

            {% for product in product %}
        <div class="my-bottom-margin col-9 col-sm-12 col-md-4 col-lg-4 col-md-auto">
                <div class="card" style="width: 18rem;">
                  <a href="{{product.get_url}}"><img class="card-img-top" src="{{product.image.url}}" alt="{{product.name}}" style="max-height:230px;"></a>
                  <div class="card-body">

                    <p class="card-text">{{product.name | truncatewords:9 }}</p>
                  </div>
                  <ul class="list-group list-group-flush">
                    <li class="list-group-item"><b>{{product.price}}</b></li>
                  </ul>
                </div>
            </div>

    </div>
    {% empty %}
    <div class="row mx-auto">
        <p class="text-center my_search_text">
        0 results found
        </p>
    </div>
    {% endfor %}
</div>

{% endblock %}